name: Deploy to Vercel

on:
  # Gatilho para push direto no repositório
  push:
    branches: [main]
    paths:
      - 'frontend/**'
      - 'Dockerfile'
      - '.github/workflows/vercel-deploy.yml'
  
  # Gatilho para execução manual via interface web
  workflow_dispatch:
    inputs:
      reason:
        description: 'Motivo do deploy manual'
        required: false
        default: 'Deploy manual via interface web'
  


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci
        
      - name: Lint and test
        working-directory: ./frontend
        run: |
          npm run lint --if-present
          npm test --if-present
          
      - name: Verify frontend configuration
        working-directory: ./frontend
        run: |
          if grep -q "homepage" package.json; then
            echo "✅ Homepage configurada no package.json"
          else
            echo "⚠️ Homepage não configurada no package.json. Isso pode causar problemas de roteamento no Vercel."
          fi
          
          if [ -f "vercel.json" ]; then
            echo "✅ Arquivo vercel.json encontrado"
          else
            echo "⚠️ Arquivo vercel.json não encontrado. Criando configuração básica..."
            # Criar vercel.json com configuração básica
            echo '{"version": 2, "builds": [{"src": "package.json", "use": "@vercel/static-build", "config": {"distDir": "build"}}], "routes": [{"src": "/static/(.*)", "dest": "/static/$1"}, {"src": "/favicon.ico", "dest": "/favicon.ico"}, {"src": "/manifest.json", "dest": "/manifest.json"}, {"src": "/logo(.*).png", "dest": "/logo$1.png"}, {"src": "/(.*)", "dest": "/index.html"}]}' > vercel.json
          fi

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        working-directory: ./frontend
        run: vercel --prod --token "${{ secrets.VERCEL_TOKEN }}" --yes
        env:
          REACT_APP_API_URL: "${{ secrets.BACKEND_URL || 'https://hope-api.up.railway.app' }}"
